# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pyinstaller pillow
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        brew install create-dmg
    - name: Build .app with pyinstaller
      run: |
        pyinstaller locatorator_mac.spec
    - name: Build DMG
      run: |
        rm -rf dist/Locatorator
        bash create_dmg.sh "locatorator_${{ github.ref_name }}_macos.dmg" dist
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "locatorator_${{ github.ref_name }}_macos.dmg"
        
  build-windows:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow
        pip install -r requirements.txt
    - name: Build with pyinstaller
      run: |
        pyinstaller locatorator_win.spec
        cd dist
#    - name: Download EnVar plugin for NSIS
#      uses: carlosperate/download-file-action@v1.0.3
#      with:
#        file-url: https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip
#        file-name: envar_plugin.zip
#        location: ${{ github.workspace }}
    - name: Create NSIS installer
      uses: joncloud/makensis-action@publish
      with:
        script-file: locatorator.nsi
#        additional-plugin-paths: ${{ github.workspace }}/NSIS_Plugins/Plugins
        arguments: "/V3"
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "dist/locatorator_setup.exe"
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "locatorator_${{ github.ref_name }}_windows.exe"
#    - name: Upload zipped app as artifact
#      uses: actions/upload-artifact@v3
#      with:
#        path: "dist/locatorator_${{ github.ref_name }}_mac.zip"
